/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jun 09 13:53:22 GMT 2023
 */

package com.google.common.jimfs;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class DowngradedSeekableByteChannel_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.google.common.jimfs.DowngradedSeekableByteChannel"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\scorz\\Desktop"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\scorz\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DowngradedSeekableByteChannel_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.common.jimfs.DowngradedSeekableByteChannel",
      "com.google.common.base.Preconditions"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DowngradedSeekableByteChannel_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.google.common.jimfs.DowngradedSeekableByteChannel",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.collect.ImmutableSortedSetFauxverideShim",
      "com.google.common.collect.ImmutableSortedSet",
      "com.google.common.collect.Ordering",
      "com.google.common.collect.NaturalOrdering",
      "com.google.common.collect.SortedIterables",
      "com.google.common.collect.Iterables",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.ImmutableList$Itr",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.RegularImmutableSortedSet",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.jimfs.PathType",
      "com.google.common.base.Joiner",
      "com.google.common.base.Splitter",
      "com.google.common.base.Platform$JdkPatternCompiler",
      "com.google.common.base.Platform",
      "com.google.common.base.CommonPattern",
      "com.google.common.base.JdkPattern",
      "com.google.common.base.CommonMatcher",
      "com.google.common.base.JdkPattern$JdkMatcher",
      "com.google.common.base.Splitter$3",
      "com.google.common.base.CharMatcher",
      "com.google.common.base.CharMatcher$FastMatcher",
      "com.google.common.base.CharMatcher$NamedFastMatcher",
      "com.google.common.base.CharMatcher$None",
      "com.google.common.jimfs.WindowsPathType",
      "com.google.common.jimfs.Name$1",
      "com.google.common.collect.ByFunctionOrdering",
      "com.google.common.jimfs.Name$2",
      "com.google.common.jimfs.Name",
      "com.google.common.collect.NullsLastOrdering",
      "com.google.common.collect.LexicographicalOrdering",
      "com.google.common.jimfs.PathService$1",
      "com.google.common.jimfs.PathService",
      "com.google.common.collect.RegularImmutableSet",
      "com.google.common.collect.Hashing",
      "com.google.common.jimfs.Util",
      "com.google.common.collect.FluentIterable",
      "com.google.common.collect.Iterables$4",
      "com.google.common.base.Optional",
      "com.google.common.base.Absent",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.AbstractIterator",
      "com.google.common.collect.Iterators$5",
      "com.google.common.collect.AbstractIterator$State",
      "com.google.common.collect.AbstractIterator$1",
      "com.google.common.collect.NullnessCasts",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.collect.ImmutableCollection$ArrayBasedBuilder",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.jimfs.JimfsPath",
      "com.google.common.jimfs.Handler",
      "com.google.common.jimfs.JimfsFileSystemProvider",
      "com.google.common.jimfs.Configuration",
      "com.google.common.base.CharMatcher$Is",
      "com.google.common.base.Splitter$1",
      "com.google.common.jimfs.UnixPathType",
      "com.google.common.jimfs.Configuration$Builder",
      "com.google.common.jimfs.SystemFileTimeSource",
      "com.google.common.jimfs.WatchServiceConfiguration$PollingConfig",
      "com.google.common.jimfs.WatchServiceConfiguration",
      "com.google.common.collect.Lists",
      "com.google.common.collect.Lists$OnePlusArrayList",
      "com.google.common.math.IntMath",
      "com.google.common.primitives.IntsMethodsForWeb",
      "com.google.common.primitives.Ints",
      "com.google.common.jimfs.PathType$ParseResult",
      "com.google.common.base.Splitter$5",
      "com.google.common.base.AbstractIterator",
      "com.google.common.base.Splitter$SplittingIterator",
      "com.google.common.base.Splitter$1$1",
      "com.google.common.base.AbstractIterator$State",
      "com.google.common.base.AbstractIterator$1",
      "com.google.common.collect.SingletonImmutableSet",
      "com.google.common.jimfs.Feature",
      "com.google.common.collect.Sets",
      "com.google.common.collect.ImmutableEnumSet",
      "com.google.common.collect.ImmutableMap",
      "com.google.common.collect.RegularImmutableMap",
      "com.google.common.jimfs.Configuration$UnixHolder",
      "com.google.common.jimfs.Configuration$1",
      "com.google.common.jimfs.Configuration$OsxHolder",
      "com.google.common.collect.Platform",
      "com.google.common.base.Splitter$3$1",
      "com.google.common.jimfs.Configuration$WindowsHolder",
      "com.google.common.base.NullnessCasts",
      "com.google.common.collect.Iterators$9",
      "com.google.common.collect.ImmutableList$SubList",
      "com.google.common.collect.ImmutableSet$Builder",
      "com.google.common.collect.ImmutableSortedSet$Builder",
      "com.google.common.collect.RangeGwtSerializationDependencies",
      "com.google.common.collect.Cut",
      "com.google.common.collect.Cut$BelowAll",
      "com.google.common.collect.Cut$AboveAll",
      "com.google.common.collect.Range",
      "com.google.common.collect.Cut$BelowValue",
      "com.google.common.collect.Cut$AboveValue",
      "com.google.common.primitives.Booleans",
      "com.google.common.collect.DiscreteDomain",
      "com.google.common.collect.ContiguousSet",
      "com.google.common.collect.RegularContiguousSet",
      "com.google.common.collect.AbstractSequentialIterator",
      "com.google.common.collect.RegularContiguousSet$1",
      "com.google.common.collect.EmptyContiguousSet",
      "com.google.common.base.Ascii",
      "com.google.common.collect.Range$1",
      "com.google.common.base.Strings",
      "com.google.common.collect.Iterators$1",
      "com.google.common.jimfs.Options",
      "com.google.common.collect.ComparisonChain$1",
      "com.google.common.collect.ComparisonChain$InactiveComparisonChain",
      "com.google.common.collect.ComparisonChain",
      "com.google.common.jimfs.FileTree",
      "com.google.common.collect.ImmutableSortedMapFauxverideShim",
      "com.google.common.collect.ImmutableSortedMap",
      "com.google.common.jimfs.HeapDisk",
      "com.google.common.math.LongMath",
      "com.google.common.jimfs.File",
      "com.google.common.jimfs.RegularFile",
      "com.google.common.jimfs.FileFactory",
      "com.google.common.jimfs.FileFactory$DirectorySupplier",
      "com.google.common.jimfs.FileFactory$RegularFileSupplier"
    );
  }
}
