/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 09 13:56:36 GMT 2023
 */

package com.google.common.jimfs;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.common.collect.ImmutableSet;
import com.google.common.collect.ImmutableSortedMap;
import com.google.common.jimfs.Directory;
import com.google.common.jimfs.File;
import com.google.common.jimfs.FileLookup;
import com.google.common.jimfs.UnixAttributeProvider;
import com.google.common.jimfs.UnixFileAttributeView;
import java.nio.file.attribute.FileAttributeView;
import java.nio.file.attribute.FileTime;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UnixAttributeProvider_ESTest extends UnixAttributeProvider_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      ImmutableSet<String> immutableSet0 = unixAttributeProvider0.fixedAttributes();
      assertEquals(8, immutableSet0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      // Undeclared exception!
      try { 
        unixAttributeProvider0.set((File) null, "", "", "", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cannot set attribute ':'
         //
         verifyException("com.google.common.jimfs.AttributeProvider", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      Object object0 = unixAttributeProvider0.get((File) null, "rdev");
      assertNotNull(object0);
      assertEquals(0L, object0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      // Undeclared exception!
      try { 
        unixAttributeProvider0.get((File) null, "ino");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.jimfs.UnixAttributeProvider", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      Directory directory0 = Directory.create(65535, (FileTime) null);
      // Undeclared exception!
      try { 
        unixAttributeProvider0.get(directory0, "gid");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      Object object0 = unixAttributeProvider0.get((File) null, ".nullsLast()");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      Directory directory0 = Directory.create(1073741824, (FileTime) null);
      Object object0 = unixAttributeProvider0.get(directory0, "dev");
      assertEquals(1L, object0);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      // Undeclared exception!
      try { 
        unixAttributeProvider0.set((File) null, "V|GMfF", "`|ycL;-0'#5#", unixAttributeProvider0, true);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // cannot set attribute 'V|GMfF:`|ycL;-0'#5#' during file creation
         //
         verifyException("com.google.common.jimfs.AttributeProvider", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      Class<UnixFileAttributeView> class0 = unixAttributeProvider0.viewType();
      assertFalse(class0.isAnnotation());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      String string0 = unixAttributeProvider0.name();
      assertEquals("unix", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      ImmutableSet<String> immutableSet0 = unixAttributeProvider0.inherits();
      assertEquals(3, immutableSet0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      UnixAttributeProvider unixAttributeProvider0 = new UnixAttributeProvider();
      FileLookup fileLookup0 = mock(FileLookup.class, new ViolatedAssumptionAnswer());
      ImmutableSortedMap<String, FileAttributeView> immutableSortedMap0 = ImmutableSortedMap.of();
      // Undeclared exception!
      try { 
        unixAttributeProvider0.view(fileLookup0, immutableSortedMap0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.jimfs.UnixAttributeProvider", e);
      }
  }
}
