/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jun 09 13:50:05 GMT 2023
 */

package com.google.common.jimfs;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Util_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.google.common.jimfs.Util"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\scorz\\Desktop"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\scorz\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Util_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.common.collect.AllEqualOrdering",
      "com.google.common.collect.ImmutableList$Itr",
      "com.google.common.collect.ImmutableList$SubList",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.jimfs.Util",
      "com.google.common.collect.RegularImmutableSortedMultiset",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.SortedMultiset",
      "com.google.common.collect.ImmutableMultiset$EntrySet",
      "com.google.common.collect.ImmutableMultisetGwtSerializationDependencies",
      "com.google.common.collect.ImmutableList$ReverseImmutableList",
      "com.google.common.collect.DescendingImmutableSortedMultiset",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.base.Converter",
      "com.google.common.collect.NullsLastOrdering",
      "com.google.common.collect.Platform",
      "com.google.common.collect.IndexedImmutableSet",
      "com.google.common.collect.RegularImmutableMultiset",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.base.Function",
      "com.google.common.collect.ComparatorOrdering",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.Multisets",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.collect.Multiset$Entry",
      "com.google.common.collect.ByFunctionOrdering",
      "com.google.common.primitives.Ints$IntConverter",
      "com.google.common.collect.RegularImmutableSet",
      "com.google.common.collect.ImmutableSortedMultiset$Builder",
      "com.google.common.collect.ObjectCountHashMap",
      "com.google.common.collect.BoundType",
      "com.google.common.collect.ExplicitOrdering",
      "com.google.common.collect.LexicographicalOrdering",
      "com.google.common.collect.NullsFirstOrdering",
      "com.google.common.collect.Multiset",
      "com.google.common.collect.ImmutableSortedMultisetFauxverideShim",
      "com.google.common.collect.SingletonImmutableSet",
      "com.google.common.collect.CompoundOrdering",
      "com.google.common.base.Strings",
      "com.google.common.collect.ImmutableMultiset$Builder",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.ReverseOrdering",
      "com.google.common.collect.ImmutableMultiset",
      "com.google.common.collect.Multisets$ImmutableEntry",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.UsingToStringOrdering",
      "com.google.common.collect.ImmutableMultiset$1",
      "com.google.common.collect.Multisets$AbstractEntry",
      "com.google.common.collect.ImmutableSortedSet",
      "com.google.common.primitives.IntsMethodsForWeb",
      "com.google.common.collect.SortedMultisetBridge",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.collect.IndexedImmutableSet$1",
      "com.google.common.collect.ReverseNaturalOrdering",
      "com.google.common.primitives.Ints",
      "com.google.common.collect.ObjectCountLinkedHashMap",
      "com.google.common.collect.SortedIterable",
      "com.google.common.collect.Ordering",
      "com.google.common.collect.NaturalOrdering",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.ElementTypesAreNonnullByDefault",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.ImmutableSortedSetFauxverideShim",
      "com.google.common.collect.ImmutableSortedMultiset",
      "com.google.common.collect.RegularImmutableSortedSet"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Util_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.google.common.jimfs.Util",
      "com.google.common.base.Preconditions",
      "com.google.common.base.Strings",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.collect.ImmutableSortedSetFauxverideShim",
      "com.google.common.collect.ImmutableSortedSet",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.collect.ImmutableCollection$ArrayBasedBuilder",
      "com.google.common.collect.ImmutableSet$Builder",
      "com.google.common.collect.ImmutableSortedSet$Builder",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.collect.Ordering",
      "com.google.common.collect.NaturalOrdering",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.ImmutableList$Itr",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.RegularImmutableSortedSet",
      "com.google.common.collect.RangeGwtSerializationDependencies",
      "com.google.common.collect.Cut",
      "com.google.common.collect.Cut$BelowAll",
      "com.google.common.collect.Cut$AboveAll",
      "com.google.common.collect.Range",
      "com.google.common.collect.Cut$AboveValue",
      "com.google.common.collect.ImmutableMultisetGwtSerializationDependencies",
      "com.google.common.collect.ImmutableMultiset",
      "com.google.common.collect.ImmutableMultiset$Builder",
      "com.google.common.collect.ObjectCountHashMap",
      "com.google.common.collect.Hashing",
      "com.google.common.base.ExtraObjectsMethodsForWeb",
      "com.google.common.base.Objects",
      "com.google.common.primitives.IntsMethodsForWeb",
      "com.google.common.primitives.Ints",
      "com.google.common.collect.RegularImmutableMultiset",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.collect.ImmutableSortedMultisetFauxverideShim",
      "com.google.common.collect.ImmutableSortedMultiset",
      "com.google.common.collect.ImmutableSortedMultiset$Builder",
      "com.google.common.collect.RegularImmutableSortedMultiset",
      "com.google.common.collect.Platform",
      "com.google.common.collect.IndexedImmutableSet",
      "com.google.common.collect.ImmutableMultiset$EntrySet",
      "com.google.common.collect.IndexedImmutableSet$1",
      "com.google.common.collect.Multisets",
      "com.google.common.collect.Multisets$AbstractEntry",
      "com.google.common.collect.Multisets$ImmutableEntry",
      "com.google.common.collect.Cut$BelowValue",
      "com.google.common.primitives.Booleans",
      "com.google.common.collect.RegularImmutableMultiset$ElementSet",
      "com.google.common.collect.ObjectCountHashMap$MapEntry",
      "com.google.common.collect.AbstractMultiset",
      "com.google.common.collect.AbstractSortedMultiset",
      "com.google.common.collect.TreeMultiset",
      "com.google.common.collect.GeneralRange",
      "com.google.common.collect.TreeMultiset$AvlNode",
      "com.google.common.collect.TreeMultiset$Reference",
      "com.google.common.collect.NullnessCasts",
      "com.google.common.collect.Sets$ImprovedAbstractSet",
      "com.google.common.collect.Multisets$EntrySet",
      "com.google.common.collect.AbstractMultiset$EntrySet",
      "com.google.common.collect.TreeMultiset$2",
      "com.google.common.collect.RegularImmutableSet",
      "com.google.common.collect.ImmutableMultiset$1",
      "com.google.common.collect.SingletonImmutableSet",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.Iterators$9",
      "com.google.common.collect.Sets",
      "com.google.common.collect.ImmutableList$SubList",
      "com.google.common.collect.Lists",
      "com.google.common.collect.TreeMultiset$Aggregate",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.collect.DiscreteDomain",
      "com.google.common.collect.DiscreteDomain$IntegerDomain",
      "com.google.common.collect.Range$1",
      "com.google.common.collect.ContiguousSet",
      "com.google.common.collect.ReverseNaturalOrdering"
    );
  }
}
