name: CodeCov

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "JDK ${{ matrix.java }} on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 15 ]
        # Only test on macos and windows with a single recent JDK to avoid a
        # combinatorial explosion of test configurations.
        # Most OS-specific issues are not specific to a particular JDK version.
    runs-on: ${{ matrix.os }}
    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v3
    - name: 'Cache local Maven repository'
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-
    - name: 'Set up JDK ${{ matrix.java }}'
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: 'Install'
      shell: bash
      run: mvn -B install
    - name: run maven jacoco
      working-directory: ./jimfs
      run: mvn jacoco:report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./jimfs/target/site/jacoco/jacoco.xml
